FROM golang:1.9 AS build

RUN curl -fsSL -o /usr/local/bin/dep https://github.com/golang/dep/releases/download/v0.3.2/dep-linux-amd64 && chmod +x /usr/local/bin/dep
RUN apt-get update && apt-get install mysql-client -y

RUN mkdir -p /go/src/github.com/cludden/go-mysql
WORKDIR /go/src/github.com/cludden/go-mysql

COPY Gopkg.toml Gopkg.lock ./
RUN dep ensure -vendor-only

CMD make help